In [156]:
include("../src/FiniteFields.jl")

zp_random_symplectic_matrix (generic function with 1 method)

zp_P_matrix (generic function with 1 method)

In [158]:
n = 3
T = GF{3}
sp = zp_random_symplectic_matrix(T, n)
P = zp_P_matrix(T, n)

6×6 Array{GF{3},2}:
 GF{3}(0)  GF{3}(2)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(1)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(2)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(1)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(2)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(1)  GF{3}(0)

In [159]:
sp' * P * sp - P

6×6 Array{GF{3},2}:
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)
 GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)  GF{3}(0)

In [146]:
zp_symplectic_inner(sp[1, :], sp[3, :])

GF{3}(1)

In [107]:
sp

4×4 Adjoint{GF{3},Array{GF{3},2}}:
 GF{3}(2)  GF{3}(1)  GF{3}(2)  GF{3}(2)
 GF{3}(2)  GF{3}(2)  GF{3}(2)  GF{3}(0)
 GF{3}(1)  GF{3}(2)  GF{3}(2)  GF{3}(1)
 GF{3}(2)  GF{3}(0)  GF{3}(1)  GF{3}(0)

In [108]:
sp

4×4 Array{GF{3},2}:
 GF{3}(2)  GF{3}(2)  GF{3}(1)  GF{3}(2)
 GF{3}(1)  GF{3}(2)  GF{3}(2)  GF{3}(0)
 GF{3}(2)  GF{3}(2)  GF{3}(2)  GF{3}(1)
 GF{3}(2)  GF{3}(0)  GF{3}(1)  GF{3}(0)

In [7]:
using LinearAlgebra
function gen_X_Z(p)
    omega = exp(1im*2pi/p)
    X = zeros(ComplexF64, p, p)
    Z = zeros(ComplexF64, p, p)
    for i in 1:p
        X[i, mod(i, p) + 1] = 1
        Z[i, i] = omega^(i-1)
    end
    return X,Z
end

gen_X_Z (generic function with 1 method)

In [14]:
p = 5
X, Z = gen_X_Z(p)
(X^2*Z^1)^p

5×5 Array{Complex{Float64},2}:
 1.0-2.57555e-16im  0.0+0.0im          …  0.0+0.0im
 0.0+0.0im          1.0-2.64896e-16im     0.0+0.0im
 0.0+0.0im          0.0+0.0im             0.0+0.0im
 0.0+0.0im          0.0+0.0im             0.0+0.0im
 0.0+0.0im          0.0+0.0im             1.0-3.33067e-16im

In [9]:
Z

5×5 Array{Complex{Float64},2}:
 1.0+0.0im       0.0+0.0im             0.0+0.0im       …       0.0+0.0im
 0.0+0.0im  0.309017+0.951057im        0.0+0.0im               0.0+0.0im
 0.0+0.0im       0.0+0.0im       -0.809017+0.587785im          0.0+0.0im
 0.0+0.0im       0.0+0.0im             0.0+0.0im               0.0+0.0im
 0.0+0.0im       0.0+0.0im             0.0+0.0im          0.309017-0.951057im